"""Remote agent installation via SSH (Linux/macOS) and WinRM (Windows).

Installs desk2ha-agent on a remote machine, generates config, and
starts the agent service. Used by the Config Flow "Install Agent" path.
"""

from __future__ import annotations

import asyncio
import logging
import secrets
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger(__name__)

# Config template deployed to the remote machine
_CONFIG_TEMPLATE = """\
# Desk2HA Agent — auto-generated by HA integration
[agent]
device_name = "auto"

[http]
enabled = true
bind = "0.0.0.0"
port = {port}
auth_token = "{token}"

[mqtt]
enabled = false

[collectors]
disabled = []

[logging]
level = "INFO"
"""

# Linux/macOS install commands
_LINUX_COMMANDS = [
    # Ensure Python 3.11+ and pip
    "python3 --version",
    "python3 -m pip install --upgrade pip",
    # Install agent
    "python3 -m pip install --upgrade desk2ha-agent",
    # Create config directory
    "sudo mkdir -p /etc/desk2ha",
    "sudo tee /etc/desk2ha/config.toml > /dev/null << 'DESK2HA_EOF'\n{config}\nDESK2HA_EOF",
    # Create systemd service
    (
        "sudo tee /etc/systemd/system/desk2ha-agent.service > /dev/null << 'DESK2HA_EOF'\n"
        "[Unit]\n"
        "Description=Desk2HA Agent\n"
        "After=network-online.target\n"
        "Wants=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        "ExecStart={python} -m desk2ha_agent --config /etc/desk2ha/config.toml --service\n"
        "Restart=on-failure\n"
        "RestartSec=5\n"
        "\n"
        "[Install]\n"
        "WantedBy=multi-user.target\n"
        "DESK2HA_EOF"
    ),
    "sudo systemctl daemon-reload",
    "sudo systemctl enable desk2ha-agent",
    "sudo systemctl restart desk2ha-agent",
]

# Windows install commands (via WinRM / PowerShell)
_WINDOWS_COMMANDS = [
    "python --version",
    "python -m pip install --upgrade pip",
    "python -m pip install --upgrade desk2ha-agent",
    'New-Item -ItemType Directory -Force -Path "$env:ProgramData\\desk2ha"',
    'Set-Content -Path "$env:ProgramData\\desk2ha\\config.toml" -Value @"\n{config}\n"@',
    # Create a scheduled task to run the agent at logon (elevated, with desktop session)
    (
        "$action = New-ScheduledTaskAction -Execute 'python' "
        "-Argument '-m desk2ha_agent --config \"$env:ProgramData\\desk2ha\\config.toml\"';"
        "$trigger = New-ScheduledTaskTrigger -AtLogon;"
        "$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries "
        "-DontStopIfGoingOnBatteries -StartWhenAvailable;"
        "Register-ScheduledTask -TaskName 'Desk2HAAgent' -Action $action "
        "-Trigger $trigger -Settings $settings -RunLevel Highest -Force"
    ),
    "Start-ScheduledTask -TaskName 'Desk2HAAgent'",
]


@dataclass
class InstallResult:
    """Result of a remote installation attempt."""

    success: bool
    agent_url: str = ""
    token: str = ""
    error: str = ""
    log: str = ""


async def install_via_ssh(
    host: str,
    port: int,
    username: str,
    password: str | None = None,
    key_file: str | None = None,
    agent_port: int = 9693,
) -> InstallResult:
    """Install desk2ha-agent on a remote Linux/macOS machine via SSH."""
    try:
        import asyncssh
    except ImportError:
        return InstallResult(
            success=False,
            error="asyncssh not installed. Run: pip install asyncssh",
        )

    token = secrets.token_urlsafe(32)
    config = _CONFIG_TEMPLATE.format(port=agent_port, token=token)
    log_lines: list[str] = []

    try:
        connect_kwargs: dict[str, Any] = {
            "host": host,
            "port": port,
            "username": username,
            "known_hosts": (),  # Trust-on-first-use
        }
        if password:
            connect_kwargs["password"] = password
        if key_file:
            connect_kwargs["client_keys"] = [key_file]

        async with asyncssh.connect(**connect_kwargs) as conn:
            # Detect Python path
            python_path = "python3"
            result = await conn.run("which python3", check=False)
            if result.exit_status != 0:
                result = await conn.run("which python", check=False)
                if result.exit_status == 0:
                    python_path = "python"
                else:
                    return InstallResult(
                        success=False,
                        error="Python 3 not found on remote machine",
                    )

            for cmd_template in _LINUX_COMMANDS:
                cmd = cmd_template.format(config=config, python=python_path)
                log_lines.append(f"$ {cmd[:80]}...")
                result = await conn.run(cmd, check=False)
                if result.stdout:
                    log_lines.append(result.stdout.strip())
                if result.exit_status != 0 and result.stderr:
                    log_lines.append(f"WARN: {result.stderr.strip()}")

            # Verify agent is running
            await asyncio.sleep(3)
            result = await conn.run(
                f"curl -sf http://127.0.0.1:{agent_port}/v1/health", check=False
            )
            if result.exit_status != 0:
                return InstallResult(
                    success=False,
                    error="Agent installed but health check failed",
                    log="\n".join(log_lines),
                )

        return InstallResult(
            success=True,
            agent_url=f"http://{host}:{agent_port}",
            token=token,
            log="\n".join(log_lines),
        )

    except Exception as exc:
        return InstallResult(
            success=False,
            error=str(exc),
            log="\n".join(log_lines),
        )


async def install_via_winrm(
    host: str,
    username: str,
    password: str,
    agent_port: int = 9693,
    use_ssl: bool = False,
) -> InstallResult:
    """Install desk2ha-agent on a remote Windows machine via WinRM."""
    try:
        import winrm  # type: ignore[import-untyped]
    except ImportError:
        return InstallResult(
            success=False,
            error="pywinrm not installed. Run: pip install pywinrm",
        )

    token = secrets.token_urlsafe(32)
    config = _CONFIG_TEMPLATE.format(port=agent_port, token=token)
    log_lines: list[str] = []

    try:
        protocol = "https" if use_ssl else "http"
        winrm_port = 5986 if use_ssl else 5985
        endpoint = f"{protocol}://{host}:{winrm_port}/wsman"

        session = winrm.Session(
            endpoint,
            auth=(username, password),
            transport="ntlm",
            server_cert_validation="ignore",
        )

        for cmd_template in _WINDOWS_COMMANDS:
            cmd = cmd_template.format(config=config)
            log_lines.append(f"PS> {cmd[:80]}...")
            result = session.run_ps(cmd)
            if result.std_out:
                log_lines.append(result.std_out.decode("utf-8", errors="replace").strip())
            if result.status_code != 0 and result.std_err:
                log_lines.append(
                    f"WARN: {result.std_err.decode('utf-8', errors='replace').strip()}"
                )

        # Verify agent is running
        await asyncio.sleep(5)
        result = session.run_ps(f"Invoke-RestMethod -Uri http://127.0.0.1:{agent_port}/v1/health")
        if result.status_code != 0:
            return InstallResult(
                success=False,
                error="Agent installed but health check failed",
                log="\n".join(log_lines),
            )

        return InstallResult(
            success=True,
            agent_url=f"http://{host}:{agent_port}",
            token=token,
            log="\n".join(log_lines),
        )

    except Exception as exc:
        return InstallResult(
            success=False,
            error=str(exc),
            log="\n".join(log_lines),
        )
